# Generated by Django 4.1.7 on 2023-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('edu', 'education'), ('scifi', 'SCIFI'), ('pol', 'politics'), ('others', 'others')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
